/*
 * Jugugu密钥Fast模式
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	Phone string `json:"phone"`
	// 通过接入jugugu申请
	Account string `json:"account"`
	// 通过接入jugugu申请
	Secret string `json:"secret"`
	// int64类型
	Time int32 `json:"time"`
	// 登录或者首次登录时获得
	Token string `json:"token"`
	// 可以自由设置也可以传“”空字符串，系统随机生成，建议让系统随机生成
	Paymentpass string `json:"paymentpass"`
	// 项目方账户系统的唯一识别码，用于绑定登录jugugu系统
	Openid string `json:"openid"`
	// jugugu区块链地址，与phone对应
	From string `json:"from"`
	Unsigntxjson []string `json:"unsigntxjson"`
	// 这里填cfx即可
	Chaintype string `json:"chaintype"`
}
