/*
 * Jugugu密钥Fast模式
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject struct for InlineObject
type InlineObject struct {
	Phone string `json:"phone"`
	Address string `json:"address"`
	// 通过接入jugugu申请
	Account string `json:"account"`
	// 通过接入jugugu申请
	Secret string `json:"secret"`
	// int64类型
	Time int32 `json:"time"`
	// 通过登录获得，首次注册时也会获得
	Token string `json:"token"`
	// 项目方账户系统的唯一识别码，用于绑定登录jugugu系统
	Openid string `json:"openid"`
	// 正式网合约：cfx:acb2027ht5t916d323zjfw9knrdj42fm8ay9n7e3x0  测试网合约：cfxtest:acbk50byfusjyh7494rm8yd8xhnkdh9jyetgadzem4
	Contract string `json:"contract"`
	Nftid string `json:"nftid"`
	Codestr string `json:"codestr"`
	// 这里填cfx即可
	Chaintype string `json:"chaintype"`
}
