/*
 * Jugugu密钥Fast模式
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	Phone string `json:"phone"`
	Confluxaddress string `json:"confluxaddress"`
	Ethaddress string `json:"ethaddress"`
	Paymentpassword string `json:"paymentpassword"`
	Token string `json:"token"`
}
